# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_timestamp', models.DateTimeField()),
                ('observation_tz', models.CharField(max_length=20)),
                ('weather', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=20)),
                ('windspeed', models.IntegerField()),
                ('windspeed_gust', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('dewpoint', models.IntegerField()),
                ('feelslike', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('uv', models.IntegerField()),
                ('precip_1hr', models.IntegerField()),
                ('precip_today', models.IntegerField()),
                ('icon', models.CharField(max_length=20)),
                ('icon_url', models.URLField()),
                ('forecast_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('ampm', models.CharField(max_length=10)),
                ('icon_tf', models.CharField(max_length=20)),
                ('icon_sf', models.CharField(max_length=20)),
                ('icon_tf_url', models.URLField()),
                ('icon_sf_url', models.URLField()),
                ('title', models.CharField(max_length=20)),
                ('fcttext_metric', models.CharField(max_length=200)),
                ('pop', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('conditions', models.CharField(max_length=200)),
                ('max_windspeed', models.IntegerField()),
                ('max_winddir', models.CharField(max_length=20)),
                ('ave_windspeed', models.IntegerField()),
                ('ave_winddir', models.CharField(max_length=20)),
                ('ave_humidity', models.IntegerField()),
                ('max_humidity', models.IntegerField()),
                ('min_humidity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=20)),
                ('country_iso3116', models.CharField(max_length=20)),
                ('country_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('tz_short', models.CharField(max_length=20)),
                ('tz_long', models.CharField(max_length=64)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherApp.location'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='display_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherApp.location'),
        ),
    ]
