# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country_iso3116',
            new_name='country_iso3166',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='last_updated',
        ),
    ]
