# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0006_auto_20170330_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='api_ref_string',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
